### ISSUE TITLE
smirnoff create system thrown off by atom names

### ISSUE THREAD

**Issue by cbayly13** [open-forcefield-group/openforcefield#50] opened 2017-06-28 18:16 UTC
command:
```top, sys, xyz = create_system_from_molecule( forcefield, mol)```

threw an exception on a mol which had a repeat atom name. Two issues:
1. The exception was obfuscating:
```Exception: No provided molecule matches topology molecule:
Atom        0  HH31     0 ACE
```
note: Caitlin found an explicit test for atom name uniqueness which apparently did not fire.

2. I don't think this problem should cause a failure. First, the atom name is just baggage, why should it matter if they are unique. What if input is a pdb file which has many repeat atom names? Second, if it is so important, why not just silently rename instead of failing, or at least have a settable flag to do so automatically if needed.
[nma.mol2.zip](https://github.com/open-forcefield-group/openforcefield/files/1109763/nma.mol2.zip)

**Comment by davidlmobley** [comment] 2017-06-28 18:21
@cbayly - saw your GitHub issue. 
I can investigate why the uniqueness test is not firing. But what format is your OEMol coming in from and what is it? 

In terms of whether uniqueness should cause failure or not -- currently things are mostly set up for "small molecules" not proteins, until we have the "how to handle charging of protein residues" issue resolved. The internal infrastructure for small molecules creates atoms in OpenMM using the atom names. If the atoms have no names, or the names are not unique, this fails. For small molecules, this just means you need to assign OETriposAtomNames first or something similar. (That's what we usually do).

For proteins this obviously needs revisiting, though we're waiting to do that until the residue charging issue is resolved (or maybe Mike has already resolved it, but I haven't had time to test.)

**Comment by bannanc** [comment] 2017-06-28 19:16
Here's the exception that isn't working:
https://github.com/open-forcefield-group/openforcefield/blob/master/openforcefield/utils/utils.py#L187

Maybe using the oemol_to_openmmTop discussed in issue #48 would fix this as well?

**Comment by davidlmobley** [comment] 2017-06-28 20:24
@bannanc - yes, that would fix it. I just need a way to be able to import that so I don't have to duplicate the code here ( @nividic take note).

I think I just added that exception a few days ago. I probably should have added a test that it fired properly.

**Comment by davidlmobley** [comment] 2017-07-01 00:39
@bannanc @cbayly13 : I can't reproduce the issue wherein the Exception is not raised; when I run this test case, an Exception is raised as it should be. I suspect @cbayly13 is running an installation which is a couple of weeks old (I recently added the Exception). 

It's also worth noting that the whole issue can be avoided entirely by providing an OpenMM Topology and an OEMol and using `forcefield.createSystem` to create the system, rather than using `create_system_from_molecule`. To create your OpenMM Topology you can, for example:
a) Use OpenMM's PDBFile, which should properly handle this molecule (if dumped into PDB format), or
b) Use Gaetano's OEMol to Topology tool
c) POSSIBLY use ParmEd to make a Topology from the file (though I don't know if it will handle multi-residue mol2 files properly)

As noted on Slack, the issue is just that `create_system_from_molecule` ends up using a utility function here which turns single-residue OEMols into OpenMM Topologies. Your molecule contains multiple residues, so you need to create your OpenMM Topology via something more rigorous.

Closing this issue for now since the fix is really just to ultimately be able to import the code noted in #48 to use for Topology creation.

**Closed by davidlmobley** 2017-07-01 00:39 UTC
